import type { AuditEntry, LibrarySummary, PermissionEntry, SiteSummary } from "./types";

export const demoSites: SiteSummary[] = [
  {
    id: "bahtnet,dgcs,001",
    name: "DGCS",
    hostname: "bahtnet.sharepoint.com",
    path: "/sites/DGCS",
    status: "connected",
  },
  {
    id: "bahtnet,engineer,002",
    name: "EngineerSite",
    hostname: "bahtnet.sharepoint.com",
    path: "/sites/EngineerSite",
    status: "ready",
  },
];

export const demoLibraries: LibrarySummary[] = [
  {
    id: "lib-dgcs-confidential",
    siteId: "bahtnet,dgcs,001",
    name: "Confidential",
    itemCount: 48,
    protected: true,
    rightsPolicy: "Library RMS",
    lastScan: "Today, 15:04",
  },
  {
    id: "lib-dgcs-secret",
    siteId: "bahtnet,dgcs,001",
    name: "Secret",
    itemCount: 18,
    protected: true,
    rightsPolicy: "Library RMS",
    lastScan: "Today, 14:38",
  },
  {
    id: "lib-dgcs-shared",
    siteId: "bahtnet,dgcs,001",
    name: "Shared Documents",
    itemCount: 126,
    protected: false,
    rightsPolicy: "Standard",
    lastScan: "Yesterday, 18:22",
  },
  {
    id: "lib-eng-confidential",
    siteId: "bahtnet,engineer,002",
    name: "Confidential",
    itemCount: 63,
    protected: true,
    rightsPolicy: "Library RMS",
    lastScan: "Today, 15:12",
  },
  {
    id: "lib-eng-secret",
    siteId: "bahtnet,engineer,002",
    name: "Secret",
    itemCount: 9,
    protected: true,
    rightsPolicy: "Library RMS",
    lastScan: "Today, 13:46",
  },
];

export const demoPermissions: PermissionEntry[] = [
  {
    id: "perm-demo8-viewer",
    libraryId: "lib-dgcs-confidential",
    displayName: "Demo 8",
    email: "demo8@baht.net",
    type: "user",
    role: "viewer",
    source: "direct",
    tenant: "baht.net",
    lastActivity: "Opened 12 min ago",
  },
  {
    id: "perm-dgcs-members-editor",
    libraryId: "lib-dgcs-confidential",
    displayName: "DGCS Members",
    email: "DGCS Members",
    type: "group",
    role: "editor",
    source: "group",
    tenant: "baht.net",
    lastActivity: "Synced today",
  },
  {
    id: "perm-external-viewer",
    libraryId: "lib-dgcs-confidential",
    displayName: "TU Reviewer",
    email: "reviewer@thammasat.net",
    type: "user",
    role: "viewer",
    source: "direct",
    tenant: "external",
    lastActivity: "Pending validation",
  },
  {
    id: "perm-engineer-owner",
    libraryId: "lib-eng-confidential",
    displayName: "Engineer Owners",
    email: "Engineer Owners",
    type: "group",
    role: "owner",
    source: "group",
    tenant: "baht.net",
    lastActivity: "Synced today",
  },
  {
    id: "perm-engineer-demo8",
    libraryId: "lib-eng-confidential",
    displayName: "Demo 8",
    email: "demo8@baht.net",
    type: "user",
    role: "editor",
    source: "direct",
    tenant: "baht.net",
    lastActivity: "Downloaded 2 hr ago",
  },
];

export const demoAudit: AuditEntry[] = [
  {
    id: "audit-1",
    actor: "Admin",
    action: "Granted viewer",
    target: "demo8@baht.net",
    time: "Today, 15:15",
  },
  {
    id: "audit-2",
    actor: "System",
    action: "Detected protected library",
    target: "DGCS / Confidential",
    time: "Today, 15:04",
  },
  {
    id: "audit-3",
    actor: "Admin",
    action: "Reviewed external access",
    target: "reviewer@thammasat.net",
    time: "Today, 14:51",
  },
];
